import { Raleway } from 'next/font/google'
import '../globals.css'

const raleway = Raleway({ subsets: ['latin', 'cyrillic'] })

export const metadata = {
  title: 'next-intl',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params: {locale} }) {
  return (
    <html lang={locale}>
      <body className={raleway.className}>
        {children}
      </body>
    </html>
  )
}
